---
apiVersion: v1
kind: Namespace
metadata:
  name: registry

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: registry
  name: config
data:
  REGISTRY_AUTH_HTPASSWD_REALM:          Private Docker Registry
  REGISTRY_AUTH_HTPASSWD_PATH:           /etc/docker/auth/htpasswd
  REGISTRY_STORAGE:                      s3
  REGISTRY_STORAGE_S3_REGION:            ${S3_REGION}
  REGISTRY_STORAGE_S3_BUCKET:            ${S3_BUCKET}
  REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
  REGISTRY_REDIS_ADDR:                   redis.registry.svc:6379


---
apiVersion: v1
kind: Secret
metadata:
  namespace: registry
  name: cookie
stringData:
  value: ${HTTP_COOKIE}

---
apiVersion: v1
kind: Secret
metadata:
  namespace: registry
  name: s3
stringData:
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: registry
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache

  template:
    metadata:
      labels:
        app: cache

    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - name: redis
              containerPort: 6379
          command:
            - redis-server

---
apiVersion: v1
kind: Service
metadata:
  namespace: registry
  name: redis
spec:
  selector:
    app: cache
  ports:
    - port: 6379
      targetPort: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: registry
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry

  template:
    metadata:
      labels:
        app: registry

    spec:
      initContainers:
        - name: htpasswd
          image: tomvoboril/htpasswd

          volumeMounts:
            - name: auth
              mountPath: /auth

          env:
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth
                  key:  username

            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth
                  key:  password

          command:
            - /bin/sh
            - -c
            - |
              set -x
              htpasswd -Bnb ${AUTH_USERNAME:-} ${AUTH_PASSWORD:-} > /auth/htpasswd

      containers:
        - name: registry
          image: registry:2

          ports:
            - name: registry
              containerPort: 5000
              protocol: TCP

          volumeMounts:
            - name: auth
              mountPath: /etc/docker/auth
              readOnly: true

          envFrom:
            - configMapRef:
                name: config
          env:
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: accessKey
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: secretKey

      volumes:
        - name: auth
          emptyDir:

---
apiVersion: v1
kind: Service
metadata:
  namespace: registry
  name: registry
spec:
  selector:
    app: registry

  ports:
    - port: 80
      targetPort: registry

