apiVersion: v1
kind: Service
metadata:
  name: registry-node
  namespace: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: registry-cache-node
  namespace: registry
spec:
  type: NodePort
  selector:
    app: registry-cache
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
