apiVersion: v1
kind: Service
metadata:
  name: registry-node
  namespace: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - targetPort: registry
    nodePort: 30500
    port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-node
  namespace: registry
spec:
  type: NodePort
  selector:
    app: cache
  ports:
  - targetPort: redis
    nodePort: 30379
    port: 6379
