---
apiVersion: v1
kind: Secret
metadata:
  name: registry
  namespace: registry
type: Opaque
data:
  REGISTRY_STORAGE_S3_ACCESSKEY: #Base64 encoded Access Key ID
  REGISTRY_STORAGE_S3_BUCKET: #Base64 encoded Bucket NAME only
  REGISTRY_STORAGE_S3_REGION: #Base64 encoded Region Name
  REGISTRY_STORAGE_S3_SECRETKEY: #Base64 encoded Secret Access Key
  REGISTRY_HTTP_SECRET: #Base64 HTTP secret, random to encode stuff
---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd
  namespace: registry
type: Opaque
data:
  HTPASSWD: #Base64 encoded Htpasswd file
---
