apiVersion: v1
kind: Service
metadata:
  name: registry-node
  namespace: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: registry
    nodePort: 30500
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-node
  namespace: registry
spec:
  type: NodePort
  selector:
    app: cache
  ports:
  - port: 6379
    targetPort: redis
    nodePort: 30379
    protocol: TCP
