---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: private-docker-registry
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-docker-registry-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-docker-registry-cache
  template:
    metadata:
      labels:
        app: private-docker-registry-cache
    spec:
      containers:
      - name: private-docker-registry-cache
        image: redis
        ports:
        - containerPort: 6379
        command:
        - redis-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: private-docker-registry
  name: private-docker-registry
  namespace: private-docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-docker-registry
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: private-docker-registry
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: private-docker-registry
        env:
        - name: REGISTRY_STORAGE
          value: s3
        - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
          value: redis
        - name: REGISTRY_REDIS_ADDR
          value: private-docker-registry-cache.private-docker-registry.svc.cluster.local:6379
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        image: registry:2
        imagePullPolicy: Always
        name: private-docker-registry
        ports:
        - containerPort: 5000
          name: 5000tls
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry
          readOnly: true
        - name: htpasswd
          mountPath: /auth
        - name: certs
          mountPath: /certs
          readOnly: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: docker-registry-config
            defaultMode: 256
            optional: false
        - name: htpasswd
          secret:
            secretName: htpasswd
            items:
              - key: HTPASSWD
                path: htpasswd
        - name: certs
          secret:
            secretName: domain-tls
---

